export const categoryMeta: Record<string, { label: string; icon: string }> = {
  PERSONALITY: { label: 'Personality', icon: 'P' },
  CORE_VALUE: { label: 'Core values', icon: 'V' },
  INTEREST: { label: 'Interests', icon: 'I' },
  RELATIONSHIP_GOAL: { label: 'Relationship goals', icon: 'R' },
  PARTNER_PREFERENCE: { label: 'Partner preferences', icon: 'P' },
  COMMUNICATION_STYLE: { label: 'Communication', icon: 'C' },
  LOVE_LANGUAGE: { label: 'Love languages', icon: 'L' },
  EMOTIONAL_NEED: { label: 'Emotional needs', icon: 'E' },
  BOUNDARY: { label: 'Boundaries', icon: 'B' },
  STRENGTH: { label: 'Strengths', icon: 'S' },
  CHALLENGE: { label: 'Challenges', icon: 'C' },
  DISLIKE: { label: 'Dislikes', icon: 'D' },
  HABIT: { label: 'Habits', icon: 'H' },
  LIFESTYLE: { label: 'Lifestyle', icon: 'L' },
  PAST_EXPERIENCE: { label: 'Past experiences', icon: 'P' },
  RELATIONSHIP_PATTERN: { label: 'Relationship patterns', icon: 'R' },
  DEAL_BREAKER: { label: 'Dealbreakers', icon: '!' },
  IMPORTANT_PERSON: { label: 'Important people', icon: 'P' },
  IMPORTANT_EVENT: { label: 'Important events', icon: 'E' },
  LOCATION_PREFERENCE: { label: 'Location preferences', icon: 'L' },
  FUTURE_PLAN: { label: 'Future plans', icon: 'F' },
  OTHER: { label: 'Other', icon: 'O' },
};