ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'IMAGE';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'AUDIO';

ALTER TABLE "Message"
ADD COLUMN "mediaUrl" TEXT,
ADD COLUMN "mediaMimeType" TEXT,
ADD COLUMN "mediaSize" INTEGER,
ADD COLUMN "mediaDurationMs" INTEGER;
