export const COUNTRIES: string[] = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (DRC)',
  'Congo (Republic)',
  'Costa Rica',
  "Côte d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'North Korea',
  'South Korea',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'São Tomé and Príncipe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  Afghanistan: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'],
  Albania: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Elbasan'],
  Algeria: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Sétif'],
  Argentina: [
    'Buenos Aires',
    'Córdoba',
    'Rosario',
    'Mendoza',
    'La Plata',
    'Mar del Plata',
    'Salta',
    'San Miguel de Tucumán',
    'Bariloche',
  ],
  Armenia: ['Yerevan', 'Gyumri', 'Vanadzor'],
  Australia: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Canberra',
    'Newcastle',
    'Hobart',
    'Darwin',
  ],
  Austria: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt'],
  Azerbaijan: ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir'],
  Bahamas: ['Nassau', 'Freeport'],
  Bahrain: ['Manama', 'Riffa', 'Muharraq'],
  Bangladesh: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Barisal', 'Rangpur'],
  Barbados: ['Bridgetown'],
  Belarus: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest'],
  Belgium: [
    'Brussels',
    'Antwerp',
    'Ghent',
    'Bruges',
    'Charleroi',
    'Liège',
    'Namur',
    'Leuven',
  ],
  Belize: ['Belize City', 'Belmopan'],
  Benin: ['Cotonou', 'Porto-Novo', 'Parakou'],
  Bhutan: ['Thimphu', 'Phuntsholing'],
  Bolivia: ['La Paz', 'Santa Cruz de la Sierra', 'Cochabamba', 'Sucre', 'El Alto'],
  'Bosnia and Herzegovina': ['Sarajevo', 'Banja Luka', 'Tuzla', 'Mostar'],
  Botswana: ['Gaborone', 'Francistown', 'Maun'],
  Brazil: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Porto Alegre',
    'Goiânia',
    'Florianópolis',
    'Natal',
  ],
  Brunei: ['Bandar Seri Begawan'],
  Bulgaria: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse'],
  'Burkina Faso': ['Ouagadougou', 'Bobo-Dioulasso'],
  Burundi: ['Bujumbura', 'Gitega'],
  'Cabo Verde': ['Praia', 'Mindelo'],
  Cambodia: ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'],
  Cameroon: ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua'],
  Canada: [
    'Toronto',
    'Vancouver',
    'Montreal',
    'Calgary',
    'Ottawa',
    'Edmonton',
    'Winnipeg',
    'Quebec City',
    'Hamilton',
    'Halifax',
    'Victoria',
  ],
  Chad: ["N'Djamena", 'Moundou'],
  Chile: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Viña del Mar'],
  China: [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Hangzhou',
    'Wuhan',
    'Xi\u2019an',
    'Nanjing',
    'Chongqing',
    'Tianjin',
    'Suzhou',
    'Qingdao',
  ],
  Colombia: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Pereira'],
  Comoros: ['Moroni'],
  'Congo (DRC)': ['Kinshasa', 'Lubumbashi', 'Goma', 'Kisangani', 'Bukavu'],
  'Congo (Republic)': ['Brazzaville', 'Pointe-Noire'],
  'Costa Rica': ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Liberia'],
  "Côte d'Ivoire": ['Abidjan', 'Yamoussoukro', 'Bouaké', 'San-Pédro'],
  Croatia: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Dubrovnik', 'Zadar', 'Pula'],
  Cuba: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Varadero'],
  Cyprus: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'],
  'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc'],
  Denmark: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'],
  Djibouti: ['Djibouti City'],
  Dominica: ['Roseau'],
  'Dominican Republic': ['Santo Domingo', 'Santiago de los Caballeros', 'La Romana', 'Punta Cana'],
  Ecuador: ['Quito', 'Guayaquil', 'Cuenca', 'Loja', 'Manta'],
  Egypt: ['Cairo', 'Alexandria', 'Giza', 'Luxor', 'Aswan', 'Port Said', 'Sharm El-Sheikh'],
  'El Salvador': ['San Salvador', 'Santa Ana', 'San Miguel'],
  Eritrea: ['Asmara'],
  Estonia: ['Tallinn', 'Tartu', 'Narva', 'Pärnu'],
  Eswatini: ['Mbabane', 'Manzini'],
  Ethiopia: ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Bahir Dar'],
  Fiji: ['Suva', 'Nadi', 'Lautoka'],
  Finland: ['Helsinki', 'Espoo', 'Tampere', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti'],
  France: [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Montpellier',
    'Strasbourg',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Toulon',
    'Grenoble',
    'Dijon',
    'Angers',
    'Nîmes',
    'Aix-en-Provence',
    'Saint-Étienne',
    'Le Havre',
    'Tours',
    'Clermont-Ferrand',
    'Brest',
    'Limoges',
    'Annecy',
    'Cannes',
  ],
  Gabon: ['Libreville', 'Port-Gentil'],
  Gambia: ['Banjul', 'Serekunda'],
  Georgia: ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi'],
  Germany: [
    'Berlin',
    'Munich',
    'Hamburg',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Düsseldorf',
    'Leipzig',
    'Dortmund',
    'Essen',
    'Bremen',
    'Dresden',
    'Hanover',
    'Nuremberg',
  ],
  Ghana: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Cape Coast'],
  Greece: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Rhodes'],
  Grenada: ["St. George's"],
  Guatemala: ['Guatemala City', 'Quetzaltenango', 'Antigua Guatemala'],
  Guinea: ['Conakry'],
  'Guinea-Bissau': ['Bissau'],
  Guyana: ['Georgetown'],
  Haiti: ['Port-au-Prince', 'Cap-Haïtien', 'Jacmel'],
  Honduras: ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba'],
  'Hong Kong': ['Hong Kong', 'Kowloon', 'Tsuen Wan'],
  Hungary: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Győr'],
  Iceland: ['Reykjavík', 'Akureyri', 'Kópavogur'],
  India: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Chennai',
    'Kolkata',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Lucknow',
    'Kochi',
    'Goa',
    'Chandigarh',
    'Indore',
  ],
  Indonesia: [
    'Jakarta',
    'Surabaya',
    'Bandung',
    'Medan',
    'Semarang',
    'Makassar',
    'Denpasar',
    'Yogyakarta',
    'Palembang',
  ],
  Iran: ['Tehran', 'Mashhad', 'Isfahan', 'Shiraz', 'Tabriz', 'Karaj', 'Qom'],
  Iraq: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Najaf'],
  Ireland: ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford', 'Belfast'],
  Israel: ['Tel Aviv', 'Jerusalem', 'Haifa', 'Beer Sheva', 'Netanya', 'Eilat'],
  Italy: [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Palermo',
    'Genoa',
    'Bologna',
    'Florence',
    'Venice',
    'Bari',
    'Catania',
    'Verona',
    'Cagliari',
  ],
  Jamaica: ['Kingston', 'Montego Bay', 'Spanish Town'],
  Japan: [
    'Tokyo',
    'Osaka',
    'Kyoto',
    'Yokohama',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Sendai',
    'Hiroshima',
    'Naha',
  ],
  Jordan: ['Amman', 'Zarqa', 'Irbid', 'Aqaba'],
  Kazakhstan: ['Almaty', 'Astana', 'Shymkent', 'Karaganda', 'Aktobe'],
  Kenya: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
  Kiribati: ['Tarawa'],
  'North Korea': ['Pyongyang', 'Hamhung', 'Chongjin'],
  'South Korea': [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
    'Suwon',
    'Jeju City',
  ],
  Kosovo: ['Pristina', 'Prizren', 'Peja', 'Gjakova'],
  Kuwait: ['Kuwait City', 'Hawalli', 'Salmiya', 'Ahmadi'],
  Kyrgyzstan: ['Bishkek', 'Osh', 'Jalal-Abad'],
  Laos: ['Vientiane', 'Luang Prabang', 'Pakse', 'Savannakhet'],
  Latvia: ['Riga', 'Daugavpils', 'Liepāja', 'Jūrmala'],
  Lebanon: ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Jounieh'],
  Lesotho: ['Maseru'],
  Liberia: ['Monrovia'],
  Libya: ['Tripoli', 'Benghazi', 'Misrata', 'Sabha'],
  Liechtenstein: ['Vaduz', 'Schaan'],
  Lithuania: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'],
  Luxembourg: ['Luxembourg City', 'Esch-sur-Alzette'],
  Madagascar: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga'],
  Malawi: ['Lilongwe', 'Blantyre', 'Mzuzu'],
  Malaysia: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Johor Bahru', 'Malacca City', 'Kota Kinabalu', 'Kuching'],
  Maldives: ['Malé', 'Addu City', 'Fuvahmulah'],
  Mali: ['Bamako', 'Sikasso', 'Mopti', 'Ségou'],
  Malta: ['Valletta', 'Birkirkara', 'Sliema', 'St. Julian\u2019s'],
  'Marshall Islands': ['Majuro'],
  Mauritania: ['Nouakchott', 'Nouadhibou'],
  Mauritius: ['Port Louis', 'Curepipe', 'Vacoas', 'Quatre Bornes'],
  Mexico: [
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Cancún',
    'Tijuana',
    'Mérida',
    'Oaxaca',
    'Puerto Vallarta',
    'Querétaro',
    'León',
  ],
  Micronesia: ['Palikir'],
  Moldova: ['Chișinău', 'Bălți', 'Tiraspol'],
  Monaco: ['Monaco'],
  Mongolia: ['Ulaanbaatar', 'Erdenet', 'Darkhan'],
  Montenegro: ['Podgorica', 'Nikšić', 'Budva', 'Kotor'],
  Morocco: ['Casablanca', 'Rabat', 'Marrakech', 'Fez', 'Tangier', 'Agadir', 'Meknes', 'Oujda'],
  Mozambique: ['Maputo', 'Matola', 'Beira', 'Nampula'],
  Myanmar: ['Yangon', 'Mandalay', 'Naypyidaw', 'Bagan'],
  Namibia: ['Windhoek', 'Swakopmund', 'Walvis Bay'],
  Nauru: ['Yaren'],
  Nepal: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Chitwan'],
  Netherlands: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Tilburg',
    'Haarlem',
    'Leiden',
    'Nijmegen',
  ],
  'New Zealand': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Dunedin', 'Queenstown'],
  Nicaragua: ['Managua', 'León', 'Granada', 'Masaya'],
  Niger: ['Niamey', 'Zinder', 'Maradi'],
  Nigeria: [
    'Lagos',
    'Abuja',
    'Kano',
    'Ibadan',
    'Port Harcourt',
    'Benin City',
    'Kaduna',
    'Enugu',
    'Aba',
  ],
  'North Macedonia': ['Skopje', 'Bitola', 'Kumanovo', 'Ohrid'],
  Norway: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Tromsø', 'Kristiansand'],
  Oman: ['Muscat', 'Salalah', 'Sohar', 'Nizwa'],
  Pakistan: [
    'Karachi',
    'Lahore',
    'Islamabad',
    'Faisalabad',
    'Rawalpindi',
    'Multan',
    'Peshawar',
    'Quetta',
  ],
  Palestine: ['Gaza City', 'Ramallah', 'Hebron', 'Nablus', 'Bethlehem'],
  Panama: ['Panama City', 'Colón', 'David'],
  'Papua New Guinea': ['Port Moresby', 'Lae', 'Mount Hagen'],
  Paraguay: ['Asunción', 'Ciudad del Este', 'Encarnación'],
  Peru: ['Lima', 'Arequipa', 'Cusco', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos'],
  Philippines: [
    'Manila',
    'Quezon City',
    'Cebu City',
    'Davao City',
    'Makati',
    'Baguio',
    'Iloilo City',
  ],
  Poland: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Lublin', 'Katowice'],
  Portugal: ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Faro', 'Aveiro', 'Madeira (Funchal)'],
  'Puerto Rico': ['San Juan', 'Ponce', 'Mayagüez', 'Carolina'],
  Qatar: ['Doha', 'Al Rayyan', 'Lusail'],
  Romania: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Brașov', 'Sibiu'],
  Russia: [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Kazan',
    'Nizhny Novgorod',
    'Samara',
    'Sochi',
    'Vladivostok',
  ],
  Rwanda: ['Kigali', 'Butare', 'Gisenyi'],
  'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Abha'],
  Senegal: ['Dakar', 'Touba', 'Thiès', 'Saint-Louis'],
  Serbia: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'],
  Seychelles: ['Victoria'],
  'Sierra Leone': ['Freetown', 'Bo', 'Kenema'],
  Singapore: ['Singapore'],
  Slovakia: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra'],
  Slovenia: ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper'],
  'Solomon Islands': ['Honiara'],
  Somalia: ['Mogadishu', 'Hargeisa', 'Bosaso'],
  'South Africa': [
    'Johannesburg',
    'Cape Town',
    'Durban',
    'Pretoria',
    'Port Elizabeth',
    'Bloemfontein',
    'East London',
  ],
  'South Sudan': ['Juba', 'Malakal'],
  Spain: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Málaga',
    'Bilbao',
    'Zaragoza',
    'Palma de Mallorca',
    'Granada',
    'Alicante',
    'Murcia',
    'San Sebastián',
    'Tenerife',
  ],
  'Sri Lanka': ['Colombo', 'Kandy', 'Galle', 'Negombo', 'Jaffna'],
  Sudan: ['Khartoum', 'Omdurman', 'Port Sudan'],
  Suriname: ['Paramaribo'],
  Sweden: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Linköping', 'Örebro', 'Lund'],
  Switzerland: [
    'Zurich',
    'Geneva',
    'Basel',
    'Bern',
    'Lausanne',
    'Lucerne',
    'Lugano',
    'Winterthur',
  ],
  Syria: ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama'],
  Taiwan: ['Taipei', 'New Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu'],
  Tajikistan: ['Dushanbe', 'Khujand', 'Kulob'],
  Tanzania: ['Dar es Salaam', 'Dodoma', 'Arusha', 'Mwanza', 'Zanzibar City', 'Mbeya'],
  Thailand: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Khon Kaen', 'Hat Yai', 'Nonthaburi'],
  'Timor-Leste': ['Dili'],
  Togo: ['Lomé', 'Kara'],
  Tonga: ["Nuku'alofa"],
  'Trinidad and Tobago': ['Port of Spain', 'San Fernando', 'Chaguanas'],
  Tunisia: ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte', 'Monastir'],
  Turkey: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Bursa',
    'Antalya',
    'Adana',
    'Gaziantep',
    'Konya',
    'Mersin',
    'Bodrum',
    'Trabzon',
  ],
  Turkmenistan: ['Ashgabat', 'Turkmenabat', 'Daşoguz'],
  Uganda: ['Kampala', 'Gulu', 'Mbale', 'Mbarara', 'Jinja'],
  Ukraine: [
    'Kyiv',
    'Kharkiv',
    'Odesa',
    'Dnipro',
    'Lviv',
    'Zaporizhzhia',
    'Vinnytsia',
    'Ivano-Frankivsk',
    'Poltava',
  ],
  'United Arab Emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Al Ain'],
  'United Kingdom': [
    'London',
    'Manchester',
    'Birmingham',
    'Liverpool',
    'Glasgow',
    'Edinburgh',
    'Leeds',
    'Bristol',
    'Newcastle',
    'Sheffield',
    'Cardiff',
    'Nottingham',
    'Brighton',
    'Belfast',
  ],
  'United States': [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Francisco',
    'Miami',
    'Atlanta',
    'Boston',
    'Seattle',
    'Denver',
    'Austin',
    'Las Vegas',
    'Washington, D.C.',
    'Portland',
    'Nashville',
  ],
  Uruguay: ['Montevideo', 'Punta del Este', 'Salto', 'Paysandú'],
  Uzbekistan: ['Tashkent', 'Samarkand', 'Bukhara', 'Namangan', 'Fergana'],
  Vanuatu: ['Port Vila', 'Luganville'],
  Venezuela: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Mérida'],
  Vietnam: [
    'Ho Chi Minh City',
    'Hanoi',
    'Da Nang',
    'Hai Phong',
    'Nha Trang',
    'Can Tho',
    'Hue',
  ],
  Yemen: ['Sana\u2019a', 'Aden', 'Taiz', 'Hodeidah'],
  Zambia: ['Lusaka', 'Kitwe', 'Ndola', 'Livingstone'],
  Zimbabwe: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare'],
};