ALTER TYPE "CoachGender" ADD VALUE IF NOT EXISTS 'NON_GENDERED';
ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'FRIENDLY';
ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'EMPATHETIC';
ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'DATING_EXPERT';
ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'PROTECTIVE';
