ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MODERATOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPPORT';
CREATE TYPE "AccountStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'BANNED');
CREATE TYPE "ReportStatus" AS ENUM ('OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED');
CREATE TYPE "ReportPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
ALTER TABLE "User" ADD COLUMN "accountStatus" "AccountStatus" NOT NULL DEFAULT 'ACTIVE', ADD COLUMN "suspendedUntil" TIMESTAMP(3), ADD COLUMN "moderationReason" TEXT;
CREATE TABLE "Report" ("id" UUID NOT NULL, "reporterId" UUID NOT NULL, "reportedUserId" UUID NOT NULL, "conversationId" UUID, "messageId" UUID, "reason" TEXT NOT NULL, "description" TEXT, "priority" "ReportPriority" NOT NULL DEFAULT 'MEDIUM', "status" "ReportStatus" NOT NULL DEFAULT 'OPEN', "assignedModeratorId" UUID, "resolution" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "resolvedAt" TIMESTAMP(3), CONSTRAINT "Report_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdminNote" ("id" UUID NOT NULL, "userId" UUID NOT NULL, "authorId" UUID NOT NULL, "content" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdminNote_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" UUID NOT NULL, "actorId" UUID, "action" TEXT NOT NULL, "resource" TEXT NOT NULL, "resourceId" TEXT, "oldValue" JSONB, "newValue" JSONB, "ipAddress" TEXT, "success" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AppSetting" ("key" TEXT NOT NULL, "value" JSONB NOT NULL, "description" TEXT, "updatedBy" UUID, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AppSetting_pkey" PRIMARY KEY ("key"));
CREATE TABLE "LlmUsage" ("id" UUID NOT NULL, "userId" UUID, "feature" TEXT NOT NULL, "provider" TEXT NOT NULL, "model" TEXT NOT NULL, "inputTokens" INTEGER NOT NULL DEFAULT 0, "outputTokens" INTEGER NOT NULL DEFAULT 0, "cachedTokens" INTEGER NOT NULL DEFAULT 0, "latencyMs" INTEGER, "estimatedCost" DECIMAL(12,6), "success" BOOLEAN NOT NULL DEFAULT true, "errorCode" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LlmUsage_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Report_status_priority_createdAt_idx" ON "Report"("status", "priority", "createdAt");
CREATE INDEX "Report_reportedUserId_createdAt_idx" ON "Report"("reportedUserId", "createdAt");
CREATE INDEX "Report_assignedModeratorId_status_idx" ON "Report"("assignedModeratorId", "status");
CREATE INDEX "AdminNote_userId_createdAt_idx" ON "AdminNote"("userId", "createdAt");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE INDEX "AuditLog_actorId_createdAt_idx" ON "AuditLog"("actorId", "createdAt");
CREATE INDEX "AuditLog_resource_action_idx" ON "AuditLog"("resource", "action");
CREATE INDEX "LlmUsage_createdAt_idx" ON "LlmUsage"("createdAt");
CREATE INDEX "LlmUsage_feature_createdAt_idx" ON "LlmUsage"("feature", "createdAt");
CREATE INDEX "LlmUsage_provider_model_createdAt_idx" ON "LlmUsage"("provider", "model", "createdAt");
CREATE INDEX "LlmUsage_userId_createdAt_idx" ON "LlmUsage"("userId", "createdAt");
ALTER TABLE "Report" ADD CONSTRAINT "Report_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Report" ADD CONSTRAINT "Report_reportedUserId_fkey" FOREIGN KEY ("reportedUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Report" ADD CONSTRAINT "Report_assignedModeratorId_fkey" FOREIGN KEY ("assignedModeratorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdminNote" ADD CONSTRAINT "AdminNote_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AdminNote" ADD CONSTRAINT "AdminNote_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
