ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'BRO_VIBE';
ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'SISTER_VIBE';
ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'SERIOUS';
ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'SOFT';
ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'SARCASTIC';
ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'MORE_DIRECTIVE';
ALTER TYPE "CoachPersonality" ADD VALUE IF NOT EXISTS 'LESS_DIRECTIVE';

ALTER TABLE "Coach" ALTER COLUMN "personality" DROP NOT NULL;
ALTER TABLE "Coach" ADD COLUMN "traits" "CoachPersonality"[] NOT NULL DEFAULT ARRAY[]::"CoachPersonality"[];
UPDATE "Coach" SET "traits" = ARRAY["personality"] WHERE "personality" IS NOT NULL;
