'use client';
import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import Link from 'next/link';
import { Empty, ErrorState, Loading } from '@/components/page-state';
import { Pagination } from '@/components/ui';
import { api } from '@/lib/api';
import type { Page } from '@/lib/types';

type Match = {
  id: string;
  score: number;
  reciprocalScore: number;
  reasons: string[] | null;
  createdAt: string;
  viewedAt?: string | null;
  respondedAt?: string | null;
  response?: string | null;
  semanticScore?: number | null;
  semanticConfidence?: number | null;
  semanticModel?: string | null;
  semanticAnalysis?: { compatibleConcepts?: string[]; contradictions?: string[] } | null;
  user: { id: string; email: string; profile?: { firstName?: string; city?: string; country?: string } | null };
  matchedUser: { id: string; email: string; profile?: { firstName?: string; city?: string; country?: string } | null };
};

export default function MatchesPage() {
  const [page, setPage] = useState(1);
  const query = useQuery({
    queryKey: ['matches', page],
    queryFn: () => api<Page<Match>>(`admin/matches?page=${page}&limit=20`),
  });
  return <>
    <div className="heading"><div><h1>Matches</h1><p>Persisted Soulprint recommendations generated by the mobile app.</p></div></div>
    {query.isLoading ? <Loading /> : query.error ? <ErrorState message={query.error.message} /> : !query.data?.items.length ? <Empty label="No persisted matches yet" /> : <>
      <div className="tablewrap"><table>
        <thead><tr><th>User</th><th>Recommended</th><th>Score</th><th>DeepSeek</th><th>Reciprocal</th><th>Shared grounds</th><th>Generated</th><th>Response</th></tr></thead>
        <tbody>{query.data.items.map((match) => <tr key={match.id}>
          <td><Link className="text-link" href={`/users/${match.user.id}`}>{match.user.profile?.firstName ?? 'Profile pending'}</Link><br /><small className="muted">{match.user.email}</small></td>
          <td><Link className="text-link" href={`/users/${match.matchedUser.id}`}>{match.matchedUser.profile?.firstName ?? 'Profile pending'}</Link><br /><small className="muted">{match.matchedUser.email}</small></td>
          <td><strong>{match.score}</strong></td>
          <td>{match.semanticScore != null ? <><strong>{match.semanticScore}</strong><br /><small className="muted">{Math.round((match.semanticConfidence ?? 0) * 100)}% confidence{match.semanticModel ? ` · ${match.semanticModel}` : ''}</small></> : 'Fallback'}</td>
          <td>{match.reciprocalScore}</td>
          <td>{match.reasons?.length ? match.reasons.slice(0, 2).join(' · ') : '—'}</td>
          <td>{new Date(match.createdAt).toLocaleString()}</td>
          <td>{match.respondedAt ? `${match.response ?? 'Responded'} · ${new Date(match.respondedAt).toLocaleDateString()}` : 'Not responded'}</td>
        </tr>)}</tbody>
      </table></div>
      <Pagination data={query.data} onPageChange={setPage} />
    </>}
  </>;
}
