export const CHAT_EVENTS = {
  join: 'conversation:join',
  leave: 'conversation:leave',
  presenceGet: 'presence:get',
  send: 'message:send',
  update: 'message:update',
  delete: 'message:delete',
  read: 'message:read',
  typingStart: 'typing:start',
  typingStop: 'typing:stop',
  created: 'message:created',
  updated: 'message:updated',
  deleted: 'message:deleted',
  delivered: 'message:delivered',
  readReceipt: 'message:read',
  typingStarted: 'typing:started',
  typingStopped: 'typing:stopped',
  error: 'chat:error',
} as const;
