import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'test', 'production')
    .default('development'),
  PORT: Joi.number().port().default(3000),
  DATABASE_URL: Joi.string().uri().required(),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_REFRESH_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('30d'),
  CORS_ORIGIN: Joi.string().required(),
  GOOGLE_CLIENT_IDS: Joi.string().allow('').default(''),
  APPLE_CLIENT_IDS: Joi.string().allow('').default(''),
  RESEND_API_KEY: Joi.string().allow('').default(''),
  EMAIL_FROM: Joi.string().default('Soulmeet <noreply@soulmeet.app>'),
  EXPO_ACCESS_TOKEN: Joi.string().allow('').default(''),
  PUBLIC_BASE_URL: Joi.string().uri().default('http://localhost:3000'),
  LLM_PROVIDER: Joi.string().valid('ollama', 'deepseek', 'openai', 'openai-compatible').default('ollama'),
  LLM_BASE_URL: Joi.string().uri().default('http://localhost:11434'),
  LLM_MODEL: Joi.string().min(1).default('deepseek-v4-flash'),
  LLM_API_KEY: Joi.string().allow('').default(''),
  LLM_THINKING_ENABLED: Joi.boolean().default(false),
  OLLAMA_BASE_URL: Joi.string().uri().default('http://localhost:11434'),
  OLLAMA_MODEL: Joi.string().min(1).default('llama3.1:8b'),
  LLM_TIMEOUT_MS: Joi.number().integer().min(1000).max(300000).default(60000),
  LLM_MAX_CONCURRENCY: Joi.number().integer().min(1).max(100).default(12),
  LLM_MAX_QUEUE_SIZE: Joi.number().integer().min(1).max(10000).default(100),
  LLM_QUEUE_TIMEOUT_MS: Joi.number().integer().min(1000).max(300000).default(30000),
  LLM_INTERACTIVE_BURST: Joi.number().integer().min(1).max(100).default(8),
  LLM_DEFAULT_MAX_TOKENS: Joi.number().integer().min(64).max(65536).default(1200),
  LLM_CACHE_ENABLED: Joi.boolean().default(true),
  LLM_CACHE_TTL_SECONDS: Joi.number().integer().min(1).max(86400).default(300),
  LLM_CACHE_MAX_ENTRIES: Joi.number().integer().min(1).max(100000).default(500),
  GUIDANCE_RECENT_MESSAGES: Joi.number().integer().min(2).max(40).default(12),
  GUIDANCE_RELEVANT_MEMORIES: Joi.number().integer().min(0).max(20).default(5),
  GUIDANCE_MEMORY_CANDIDATE_LIMIT: Joi.number().integer().min(1).max(100).default(50),
  GUIDANCE_MAX_RESPONSE_TOKENS: Joi.number().integer().min(64).max(4096).default(320),
  LLM_FALLBACK_PROVIDER: Joi.string().valid('ollama', 'deepseek', 'openai', 'openai-compatible').allow('').default(''),
  LLM_FALLBACK_BASE_URL: Joi.string().uri().allow('').default(''),
  LLM_FALLBACK_MODEL: Joi.string().allow('').default(''),
  LLM_FALLBACK_API_KEY: Joi.string().allow('').default(''),
  SOULPRINT_EXTRACTION_ENABLED: Joi.boolean().default(true),
  SOULPRINT_EXTRACTION_MIN_USER_MESSAGES: Joi.number().integer().min(1).default(1),
  SOULPRINT_EXTRACTION_MIN_CHARACTERS: Joi.number().integer().min(1).default(300),
  SOULPRINT_EXTRACTION_DEBOUNCE_SECONDS: Joi.number().integer().min(0).default(2),
  SOULPRINT_EXTRACTION_MAX_MESSAGES: Joi.number().integer().min(1).max(100).default(20),
  SOULPRINT_EXTRACTION_TIMEOUT_MS: Joi.number().integer().min(1000).default(120000),
  SOULPRINT_JOB_POLL_INTERVAL_MS: Joi.number().integer().min(250).default(2000),
  SOULPRINT_JOB_CONCURRENCY: Joi.number().integer().min(1).max(32).default(4),
  SOULPRINT_JOB_MAX_ATTEMPTS: Joi.number().integer().min(1).max(20).default(5),
  SOULPRINT_JOB_BACKOFF_BASE_MS: Joi.number().integer().min(100).default(5000),
  SOULPRINT_JOB_STALE_MS: Joi.number().integer().min(1000).default(300000),
  SOULPRINT_AUTO_CONFIRM_DIRECT_FACTS: Joi.boolean().default(true),
  SOULPRINT_AUTO_SUMMARY_ENABLED: Joi.boolean().default(true),
  SOULPRINT_SUMMARY_CHANGE_THRESHOLD: Joi.number().integer().min(1).default(3),
  SOULPRINT_MAX_GUIDANCE_ENTRIES: Joi.number().integer().min(1).max(100).default(25),
  SOULPRINT_HISTORY_ENABLED: Joi.boolean().default(true),
  SOULPRINT_PROMPT_VERSION: Joi.string().default('v3'),
  SEMANTIC_MATCHING_ENABLED: Joi.boolean().default(false),
  SEMANTIC_MATCHING_PROMPT_VERSION: Joi.string().default('v1'),
  SEMANTIC_MATCHING_CANDIDATE_LIMIT: Joi.number().integer().min(1).max(25).default(10),
  SEMANTIC_MATCHING_WEIGHT: Joi.number().min(0).max(1).default(0.55),
  DAILY_COACH_MESSAGES_ENABLED: Joi.boolean().default(true),
  DAILY_COACH_MESSAGE_HOUR: Joi.number().integer().min(0).max(23).default(10),
  DAILY_COACH_POLL_INTERVAL_MS: Joi.number().integer().min(60000).default(300000),
  DAILY_COACH_MAX_ATTEMPTS: Joi.number().integer().min(1).max(10).default(3),
});
